WITH RECURSIVE HOUR AS(
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1 FROM HOUR WHERE HOUR < 23
)

SELECT HOUR.HOUR AS HOUR, COUNT(ANIMAL_OUTS.DATETIME) AS COUNT
FROM HOUR LEFT JOIN ANIMAL_OUTS ON HOUR.HOUR = HOUR(ANIMAL_OUTS.DATETIME)
GROUP BY HOUR.HOUR
ORDER BY HOUR.HOUR;